// USER
export const FETCHING_USER = 'FETCHING_USER'
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED'

// AUTH
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT = 'LOGOUT'
