// Colors
export const FETCHING_COLORS = 'FETCHING_COLORS'
export const COLORS_FETCH_SUCCESS = 'COLORS_FETCH_SUCCESS'
export const COLORS_DELETE_SUCCESS = 'COLORS_DELETE_SUCCESS'
export const COLORS_FETCH_FAILED = 'COLORS_FETCH_FAILED'

// AUTH
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT = 'LOGOUT'
